// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_ESfKhuxISul_AMzf1IJnDMzmH0tmy2M',
    appId: '1:862325738779:web:b11dc4bb6bfe54299cd7be',
    messagingSenderId: '862325738779',
    projectId: 'ulusal-barter',
    authDomain: 'ulusal-barter.firebaseapp.com',
    storageBucket: 'ulusal-barter.firebasestorage.app',
    measurementId: 'G-R19ETDCXBZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArCdfjm6ZWz8zeYA4ramY2w60M1QtzlMc',
    appId: '1:862325738779:ios:6515a8e8f727949d9cd7be',
    messagingSenderId: '862325738779',
    projectId: 'ulusal-barter',
    storageBucket: 'ulusal-barter.firebasestorage.app',
    iosBundleId: 'com.example.ulusalbarter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_ESfKhuxISul_AMzf1IJnDMzmH0tmy2M',
    appId: '1:862325738779:web:abbc31515129c57d9cd7be',
    messagingSenderId: '862325738779',
    projectId: 'ulusal-barter',
    authDomain: 'ulusal-barter.firebaseapp.com',
    storageBucket: 'ulusal-barter.firebasestorage.app',
    measurementId: 'G-WZ4Y6H0ER7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArCdfjm6ZWz8zeYA4ramY2w60M1QtzlMc',
    appId: '1:862325738779:ios:6515a8e8f727949d9cd7be',
    messagingSenderId: '862325738779',
    projectId: 'ulusal-barter',
    storageBucket: 'ulusal-barter.firebasestorage.app',
    iosBundleId: 'com.example.ulusalbarter',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVdnZ79JiblpmZFfiVl_a1d2t-ficVX9w',
    appId: '1:862325738779:android:42c6edd577e72de49cd7be',
    messagingSenderId: '862325738779',
    projectId: 'ulusal-barter',
    storageBucket: 'ulusal-barter.firebasestorage.app',
  );

}